- name: Setup Redmine
  hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      become: true
    - role: geerlingguy.pip
      pip_install_packages:
        - docker
      become: true

  tasks:
    - name: create .env file
      template:
        src: templates/.env.j2
        dest: .env
        mode: '664'
      tags: redmine

    - name: start redmine
      docker_container:
        name: redmine
        image: redmine:6.0-alpine
        state: started
        restart: true
        recreate: true
        env_file: .env
        published_ports:
          - "{{ external_port }}:3000"
      tags: redmine

- name: Install Datadog Agent
  hosts: webservers
  become: true

  roles:
    - role: datadog.dd.agent
      tags: datadog